# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{userstream}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua Hull", "Fabien Penso"]
  s.date = %q{2010-05-21}
  s.default_executable = %q{chirp_growl}
  s.description = %q{Eventmachine-based Userstream client}
  s.email = %q{joshbuddy@gmail.com}
  s.executables = ["chirp_growl"]
  s.files = [
    "Gemfile",
    "Rakefile",
    "Readme.rdoc",
    "VERSION",
    "bin/chirp_growl",
    "image/bird.png",
    "lib/userstream.rb",
    "lib/userstream/connect.rb",
    "lib/userstream/event.rb",
    "lib/userstream/event/delete.rb",
    "lib/userstream/event/direct_message.rb",
    "lib/userstream/event/favorite.rb",
    "lib/userstream/event/follow.rb",
    "lib/userstream/event/retweet.rb",
    "lib/userstream/event/unfavorite.rb",
    "lib/userstream/tweet.rb",
    "lib/userstream/twitter_object.rb",
    "lib/userstream/friend.rb",
    "lib/userstream/user.rb"
  ]
  s.homepage = %q{http://github.com/joshbuddy/userstream}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Eventmachine-based Userstream client}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.10"])
      s.add_runtime_dependency(%q<em-http-request>, [">= 0.2.7"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0.7.5"])
      s.add_runtime_dependency(%q<load_path_find>, [">= 0.0.5"])
      s.add_runtime_dependency(%q<oauth>, [">= 0.3.5"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0.12.10"])
      s.add_dependency(%q<em-http-request>, [">= 0.2.7"])
      s.add_dependency(%q<yajl-ruby>, [">= 0.7.5"])
      s.add_dependency(%q<load_path_find>, [">= 0.0.5"])
      s.add_dependency(%q<oauth>, [">= 0.4.0"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0.12.10"])
    s.add_dependency(%q<em-http-request>, [">= 0.2.7"])
    s.add_dependency(%q<yajl-ruby>, [">= 0.7.5"])
    s.add_dependency(%q<load_path_find>, [">= 0.0.5"])
    s.add_dependency(%q<oauth>, [">= 0.4.0"])
  end
end

